# Generated by Django 2.2.7 on 2019-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_annualincome_name_ssn_workingyears'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='workingyears',
            name='SSN',
        ),
        migrations.AddField(
            model_name='platform',
            name='annualincome_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='platform',
            name='name_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='platform',
            name='ssn_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='platform',
            name='workingyears_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.DeleteModel(
            name='AnnualIncome',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='SSN',
        ),
        migrations.DeleteModel(
            name='WorkingYears',
        ),
    ]
