# Generated by Django 2.2.7 on 2019-11-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20191121_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='annualincome_text',
            new_name='annualincome',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='ssn_text',
            new_name='ssn',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='workingyears_text',
            new_name='workingyears',
        ),
    ]
