# Generated by Django 2.2.7 on 2019-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20191121_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='pred',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
