# Generated by Django 2.2.7 on 2019-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20191122_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='predloan',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
