# Generated by Django 3.0.6 on 2020-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_auto_20200529_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
