# Generated by Django 3.0.6 on 2020-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0003_auto_20200529_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
